modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"

[[mods]]
modId="entitled"
version="1.2.1"
displayName="Entitled"
displayURL="https://github.com/CleverNucleus/Entitled"
logoFile="logo.png"
credits="CleverNucleus"
authors="CleverNucleus"

description='''
Allows the player to use a nametag as a title for themselves, which is displayed below their ingame nametag.
'''

[[dependencies.entitled]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.entitled]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"