modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="entitled"
version="1.1.0"
displayName="Entitled"
displayURL="https://github.com/CleverNucleus/Entitled"
logoFile="logo.png"
credits="CleverNucleus; shout-out to icey__1992 for suggesting a cool idea to implement."
authors="CleverNucleus"

description='''
Allows the player to use a nametag as a title for themselves, which is displayed below their ingame nametag.
'''

[[dependencies.adiectamateria]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crucible]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"